### ISSUE TITLE
No datasources!

### ISSUE THREAD

**Issue by JonnyHayes** [mikesprague/lucee5-heroku#2]
Hi -  there are no datasource types available in this build. Not even 'other'
thanks

![screen shot 2015-06-12 at 4 35 08 pm](https://cloud.githubusercontent.com/assets/1776698/8142690/220f2efa-1121-11e5-94a4-a526845e7d85.png)

**Comment by mikesprague** [comment]
Hi @JonnyHayes , Lucee 5 does everything, including MySQL datasources, via extensions. I'll look into adding datasources when the next beta of Lucee 5 is released with this support.
