### ISSUE TITLE
Occasional application error if Heroku instance has been asleep

### ISSUE THREAD

**Issue by mikesprague** [mikesprague/lucee5-heroku#5]
🔄 Reloading the page in the browser allows the app to load properly and the error goes away.

Need to check Heroku logs and research further to determine if there's anything I can on my end to prevent this.

**Comment by timsayshey** [comment]
Looks like this is due to Heroku's 30 request timeout. I wonder if there is a way to speed up Lucee's initial request by adjusting the JVM settings, etc.

**Comment by mikesprague** [comment]
@timsayshey Yeah, I think you're right. I'm no JVM expert and since Lucee downloads it's dependencies I'm not sure what the best approach would be yet.

This article looks like it could be promising but I haven't had time to implement/test it yet:
- https://devcenter.heroku.com/articles/warming-up-a-java-process
